[theme]
# Azul corporativo Power BI
primaryColor = "#FF00FF"

# Fondo general (blanco humo Power BI)
backgroundColor = "#32CD32"

# Sidebar blanco limpio
secondaryBackgroundColor = "#FFFF00"

# Texto oscuro profesional
textColor = "#0000FF"

# Fuente base
font = "serif"
