[theme]
# 1. Primario: Magenta Ne√≥n
primaryColor = "#D500F9"

# 2. Fondo Principal: Gris Espacial (Oscuro suave)
backgroundColor = "#212121"

# 3. Barra Lateral: Violeta Profundo
secondaryBackgroundColor = "#311B92"

# 4. Texto: Blanco Perla
textColor = "#ECEFF1"

# 5. Fuente
font = "sans serif"
