[theme]
# 1. Primario: Turquesa Brillante (Como un marcador resaltador)
primaryColor = "#00B0FF"

# 2. Fondo Principal: Azul Alicia (Muy p√°lido, casi blanco)
backgroundColor = "#F0F8FF"

# 3. Barra Lateral: Azul Marino Real (Autoridad)
secondaryBackgroundColor = "#0D47A1"

# 4. Texto: Azul Medianoche
textColor = "#01579B"

# 5. Fuente
font = "sans serif"
