[theme]
# Color principal (para los acentos y bordes al pasar el mouse)
primaryColor = "#2962FF"

# El color de fondo exacto de la referencia (Gris muy suave)
backgroundColor = "#F0F2F6"

# El color de la barra lateral (Un blanco puro para contraste)
secondaryBackgroundColor = "#FFFFFF"

# Color del texto
textColor = "#263238"

# Tipograf√≠a
font = "sans serif"
