[theme]
# 1. Color Primario
primaryColor = "#FF4B4B"

# 2. Fondo Principal (NEGRO PURO)
# Si esto funciona, tu pantalla se pondr√° negra.
backgroundColor = "#000000"

# 3. Barra Lateral (Gris Oscuro)
secondaryBackgroundColor = "#262730"

# 4. Texto (Blanco)
textColor = "#FFFFFF"

# 5. Fuente
font = "sans serif"
