[theme]
# Azul corporativo Power BI
primaryColor = "#FF8C00"

# Fondo general (blanco humo Power BI)
backgroundColor = "#FAFAFA"

# Sidebar blanco limpio
secondaryBackgroundColor = "#FFF3E0"

# Texto oscuro profesional
textColor = "#262730"

# Fuente base
font = "serif"

runOnSave = true
