[theme]
# 1. Color Primario (Acentos)
primaryColor = "#2962FF"

# 2. Color de Fondo (EL CAMBIO CLAVE)
# Este es un Gris Azulado con más "peso".
# Hará que las tarjetas blancas resalten muchísimo más.
backgroundColor = "#FFF4E6"

# 3. Barra Lateral
# Blanco Puro para crear el marco limpio a la izquierda
secondaryBackgroundColor = "#FFFFFF"

# 4. Texto
textColor = "#263238"

# 5. Fuente
font = "sans serif"
