[theme]
# 1. Primario: √Åmbar Dorado (Da un toque de "Premium")
primaryColor = "#FFAB00"

# 2. Fondo Principal: Blanco (Limpio para leer)
backgroundColor = "#FFFFFF"

# 3. Barra Lateral: Azul Marino Profundo (El toque elegante)
secondaryBackgroundColor = "#1A237E"

# 4. Texto: Azul Noche (En lugar de negro)
textColor = "#0D47A1"

# 5. Fuente
font = "sans serif"
