[theme]
# Azul corporativo Power BI
primaryColor = "#0078D4"

# Fondo general (blanco humo Power BI)
backgroundColor = "#F9FAFB"

# Sidebar blanco limpio
secondaryBackgroundColor = "#FFFFFF"

# Texto oscuro profesional
textColor = "#1F2937"

# Fuente base
font = "sans serif"
