[theme]
# 1. Primario: Turquesa Neón (Resalta muchísimo sobre oscuro)
primaryColor = "#00E5FF"

# 2. Fondo Principal: Gris muy oscuro (Casi negro, estilo VS Code)
backgroundColor = "#1E1E1E"

# 3. Barra Lateral: Negro Puro (Profundidad)
secondaryBackgroundColor = "#121212"

# 4. Texto: Blanco Humo (Lectura cómoda en fondo oscuro)
textColor = "#FAFAFA"

# 5. Fuente
font = "sans serif"
