[theme]
# Azul corporativo Power BI
primaryColor = "#FF8C00"

# Fondo general (blanco humo Power BI)
backgroundColor = "#FFFFFF"

# Sidebar blanco limpio
secondaryBackgroundColor = "#F0F2F6"

# Texto oscuro profesional
textColor = "#262730"

# Fuente base
font = "serif"

runOnSave = true
