[theme]
# Azul corporativo Power BI
primaryColor = "#2962FF"

# Fondo general (blanco humo Power BI)
backgroundColor = "#E1E4E8"

# Sidebar blanco limpio
secondaryBackgroundColor = "#FFFFFF"

# Texto oscuro profesional
textColor = "#263238"

# Fuente base
font = "sans serif"
