[theme]
# 1. Primario: Lima Vibrante (Muy llamativo para botones)
primaryColor = "#00C853"

# 2. Fondo Principal: Blanco Nieve (MÃ¡xima limpieza)
backgroundColor = "#FFFFFF"

# 3. Barra Lateral: Negro Pizarra (Contrastado y elegante)
secondaryBackgroundColor = "#263238"

# 4. Texto: Gris Oscuro
textColor = "#37474F"

# 5. Fuente
font = "sans serif"
